#!/bin/bash

set -e

eval export JAVA_HOME=\$JAVA_${QBT_ENV_JDK:-1_8}_HOME

# test
if [ -d test ]; then "$INPUT_ARTIFACTS_DIR"/weak/qbt_fringe.linter.release/strong/qbt_fringe.linter.release/bin/linter -d test; fi
"$INPUT_ARTIFACTS_DIR"/weak/3p.gradle/strong/3p.gradle/bin/gradle --stacktrace check
